title: Vincent Havard
description: Page in construction
theme: just-the-docs

url: https://vhavard.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
